services:
  api:
    image: ${AIRDANCER_IMAGE:-ghcr.io/larsks/airdancer:latest}
    volumes:
      - './config:/config'
    command:
    - airdancer-api
    - --config
    - /config/airdancer-api.toml
    ports:
      - "8080:8080"
    devices:
    - /dev/gpiochip0
  ui:
    image: ${AIRDANCER_IMAGE:-ghcr.io/larsks/airdancer:latest}
    volumes:
      - './config:/config'
    command:
    - airdancer-ui
    - --config
    - /config/airdancer-ui.toml
  caddy:
    image: docker.io/caddy:latest
    volumes:
      - './config:/etc/caddy'
    ports:
    - "80:80"
  buttons:
    image: ${AIRDANCER_IMAGE:-ghcr.io/larsks/airdancer:latest}
    volumes:
      - './config:/config'
    environment:
      DANCER_SERVER_URL: http://airdancer-api:8080
    command:
    - airdancer-buttons
    - --config
    - /config/airdancer-buttons.toml
    devices:
    - /dev/input/by-id/usb-Microntek_USB_Joystick-event-joystick
  status:
    network_mode: host
    image: ${AIRDANCER_IMAGE:-ghcr.io/larsks/airdancer:latest}
    volumes:
      - './config:/config'
    command:
    - airdancer-status
    - --config
    - /config/airdancer-status.toml
    devices:
    - /dev/i2c-1
  soundboard:
    image: ${AIRDANCER_IMAGE:-ghcr.io/larsks/airdancer:latest}
    volumes:
      - './config:/config'
      - './clips:/clips'
    command:
    - airdancer-soundboard
    - --config
    - /config/airdancer-soundboard.toml
    devices:
    - /dev/snd/controlC0
    - /dev/snd/controlC1
    - /dev/snd/pcmC0D0p
    - /dev/snd/pcmC1D0p
    - /dev/snd/seq
    - /dev/snd/timer
  nanomq:
    image: docker.io/emqx/nanomq:latest
    ports:
    - "1883:1883"
