listen-address = ""
listen-port = 8080

[collections.frontpanel]
driver = 'dummy'

[collections.frontpanel.driverconfig]
switch_count = 4

[collections.backpanel]
driver = 'dummy'

[collections.backpanel.driverconfig]
switch_count = 4

[switches.lamp1]
spec = "frontpanel.0"

[switches.lamp2]
spec = "frontpanel.3"

[switches.lamp3]
spec = "backpanel.0"
