[imap]
server = "imap"
port = 31143
username = "dancer"
password = "password"
use-ssl = false

retry-interval-seconds = 2
check-interval-seconds = 10

[[monitor]]
mailbox = "INBOX"

[[monitor.triggers]]
command = "dancerctl --server-url http://airdancer-api:8080 blink green --period 5 --duration 20"
regex-pattern = 'blink switch'
