# Example configuration for airdancer-buttons

[[buttons]]
name = "Power"
device = "/dev/input/by-id/usb-Microntek_USB_Joystick-event-joystick"
event_type = "EV_KEY"
event_code = 289
click_action = "notify-send 'CLICK'"
double_click_action = "notify-send 'DOUBLE CLICK'"
triple_click_action = "notify-send 'TRIPLE_CLICK'"
short_press_action = "notify-send 'SHORT PRESS'"
short_press_duration = 2
long_press_action = "notify-send 'LONG PRESS'"
long_press_duration = 5
timeout = 10
