# Example configuration for airdancer-monitor

# IMAP server configuration
[imap]
server = "imap.gmail.com"
port = 993
username = "your-email@gmail.com"
password = "your-app-password"
use_ssl = true
mailbox = "INBOX"
check_interval_seconds = 30

# Monitor configurations - you can define multiple monitors for different patterns
[[monitor]]
regex_pattern = "activate switch (\\d+)"
command = "echo 'Switch activation request: $1'"

[[monitor]]
regex_pattern = "CRITICAL.*ERROR"
command = "notify-send 'Critical Alert' 'Error detected in email'"

[[monitor]]
regex_pattern = "backup.*complete"
command = "logger 'Backup notification received'" 