listen-address = ""
listen-port = 8080

[collections.frontpanel]
driver = 'dummy'

[collections.frontpanel.driverconfig]
switch-count = 4

[collections.backpanel]
driver = 'dummy'

[collections.backpanel.driverconfig]
switch-count = 4

[collections.gpiopanel]
driver = 'gpio'

[collections.gpiopanel.driverconfig]
pins = ["GPIO18", "GPIO19", "GPIO20", "GPIO21"]

[switches.lamp1]
spec = "frontpanel.0"

[switches.lamp2]
spec = "frontpanel.3"

[switches.lamp3]
spec = "backpanel.0"

[switches.airdancer]
spec = "backpanel.1"

[switches.gpio-switch1]
spec = "gpiopanel.0"

[switches.gpio-switch2]
spec = "gpiopanel.1"