[[buttons]]
name = "PowerButton"
driver = "gpio"
spec = "GPIO16:active-low:pull-up"
click_action = "echo 'Power button clicked'"
long_press_action = "shutdown -h now"
long_press_duration = "3s"

[[buttons]]
name = "VolumeUp"
driver = "event"
spec = "/dev/input/event0:EV_KEY:115:0:1"
click_action = "amixer set Master 5%+"
