short_press_duration = "2s"
long_press_duration = "5s"
timeout = "10s"

[[buttons]]
name = "Blue"
driver = "event"
spec = "/dev/input/by-id/usb-Microntek_USB_Joystick-event-joystick:EV_KEY:288"
click_action = "xh -I localhost:8080/switch/0 state=on duration:=10"
short_press_action = "/home/dancer/pfctl blink 7:500ms:0.5 --duration 2s; sudo reboot"
long_press_action = "/home/dancer/pfctl blink 7:250ms:0.2 --duration 2s; sudo poweroff"

[[buttons]]
name = "Green"
driver = "event"
spec = "/dev/input/by-id/usb-Microntek_USB_Joystick-event-joystick:EV_KEY:289"
click_action = "xh -I localhost:8080/switch/1 state=on duration:=10"
short_press_action = "sudo systemctl restart airdancer-wifi-fallback.service"
