name: Build
on:
  push:
    branches:
      - "*"
    paths:
    - '**/*.go'
  pull_request:
    paths:
    - '**/*.go'
  workflow_call:

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: build
        run: |
          make all
